### ISSUE TITLE
Look at MindPointGroup

### ISSUE THREAD

**Issue by bbaassssiiee** [ComplianceAsCode/ansible-compliance#1]
https://github.com/MindPointGroup/RHEL7-STIG

**Comment by bbaassssiiee** [comment]
https://github.com/MindPointGroup/RHEL7-STIG

**Comment by redhatrises** [comment]
Thanks but MindPointGroup is not upstream from Red Hat or supported by Red Hat or responsible for generating Red Hat STIGs. This organization is.

**Comment by bbaassssiiee** [comment]
They were assigned by Ansible Inc. https://ansiblelockdown.io

**Comment by redhatrises** [comment]
The content from this org is what Red Hat officially submits to the US Government, other governments, and certification entities. It is not only certified by these entities but is also recognized as the official vendor supported content and guidance. Many of the collaborators actually help to write the government security profiles that are implemented by other vendors and customers.

**Comment by bbaassssiiee** [comment]
This ansible repo doesn't have so much content. (sic.)
